name: pks-0637-psf-check
sub_name: psf-marx-no-pileup
path_data: data
obs_ids:
- 19692
obs_id_ref: 19692
roi:
    center:
        frame: icrs
        lon: 6h35m46.50793015s
        lat: -75d16m16.81641826s
    width: 5arcsec
    bin_size: 0.25
    energy_range:
        min: 0.5 keV
        max: 7.0 keV
psf_simulator: marx
irfs:
    pks-0637-marx-no-pileup-blur-0.07:
        spectrum:
            background_region_file: bkg-region.reg 
        psf:
            minsize: 128
            numiter: 20
            numsig: 7
            blur: 0.07
    pks-0637-marx-no-pileup-blur-0.115:
        spectrum:
            background_region_file: bkg-region.reg 
        psf:
            minsize: 128
            numiter: 20
            numsig: 7
            blur: 0.115
    pks-0637-marx-no-pileup-blur-0.16:
        spectrum:
            background_region_file: bkg-region.reg 
        psf:
            minsize: 128
            numiter: 20
            numsig: 7
            blur: 0.16
    pks-0637-marx-no-pileup-blur-0.205:
        spectrum:
            background_region_file: bkg-region.reg 
        psf:
            minsize: 128
            numiter: 20
            numsig: 7
            blur: 0.205
    pks-0637-marx-no-pileup-blur-0.25:
        spectrum:
            background_region_file: bkg-region.reg 
        psf:
            minsize: 128
            numiter: 20
            numsig: 7
            blur: 0.25
ciao:
    chandra_repro:
        pix_adj: none
